apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-apps
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       e-commerce-odoo
  updatePolicy:
    updateMode: "Auto"